### ISSUE TITLE
No resolution of network hostname in Docker Beta

### ISSUE THREAD

**Issue by NickClark** [jwilder/dockerize#41]
When I have a compose file (version 2), that uses the default Docker networking and defines a service of `db` and `app`, I can `ping db` from the `app` container, but when I do `dockerize -wait tcp://db:5432`, it never finds it. Pinging reveals that `db` gets translated to something like `server_db_1.server_default`. Using that hostname works with `dockerize`. Is this a Docker Networking or Docker Beta issue?

**Comment by NickClark** [comment]
Using the following workaround for now:

`getent hosts db | cut -d " " -f 1`

**Comment by ismarslomic** [comment]
@NickClark: I have related issue, see #63 . Did you experience same thing, and do you possibly have an workaround?

**Comment by binhnv** [comment]
I am having the same issue with any Docker version that is newer than 1.12.5

**Comment by jwilder** [comment]
This sounds like an issue with how your contains are started or something do to with docker networking.  From:

https://docs.docker.com/engine/userguide/networking/#the-default-bridge-network

> Containers connected to the default bridge network can communicate with each other by IP address. Docker does not support automatic service discovery on the default bridge network. If you want containers to be able to resolve IP addresses by container name, you should use user-defined networks instead.

`dockerize` doesn't do any DNS resolution itself so I don't think this issue is an issue with `dockerize` itself.

**Comment by binhnv** [comment]
The issue was not because of default network since I am not using it.
It turns out it was because of the timeout. I set timeout to 2s and it has been working fine with Docker for Mac version 1.12.5 or older versions but it did not work on newer versions. For newer versions I changed timeout to 10s and it works fine again.
